name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        
      - name: Anilist_Spotify
        uses: lowlighter/metrics@latest
        with:
          filename: /.github/workflows/anilist_spotify.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 3
          plugin_anilist_user: julioCROS
          plugin_music: yes
          plugin_music_provider: spotify
          config_order: anilist, music
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_mode: recent
          plugin_music_limit: 5
