name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
    - name: General
      uses: lowlighter/metrics@latest
      with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, repositories, metadata
          base_indepth: yes
          config_order: base.header, isocalendar, languages
          plugin_languages: yes
          plugin_languages_ignored: pawn, css, makefile, qmake, coq, jupyter notebook, tcl,
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 5

    - name: Anilist_Spotify
      uses: lowlighter/metrics@latest
      with:
          filename: anilist_spotify.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 3
          plugin_anilist_user: julioCROS
          plugin_music: yes
          plugin_music_provider: spotify
          config_order: anilist, music
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_mode: recent
          plugin_music_limit: 5
